### ISSUE TITLE
Style + simple copy changes for marketing site

### ISSUE THREAD

**Issue by msknee** [codeforamerica/cleaning-pgh#15]
![marketing-01](https://cloud.githubusercontent.com/assets/1178390/6910224/5ebe5336-d705-11e4-99de-dd44cac5fac7.png)

![marketing-02](https://cloud.githubusercontent.com/assets/1178390/6910239/8a888720-d705-11e4-8836-f62da2186439.png)
### Style changes:
- [x] Increase height of email sign up field and "subscribe" button by 2x, to 60px when viewed on a desktop
- [x] Change color of subscribe button to: #FFFF00
- [x] Yellow header text is also #FFFF00 
- [x] Create green header div with this color: #009145 
- [x] Text in green header is size 36px, and both Bold and Regular (see mockup)
- [x] Swap in logo with white text
- [x] Background color of the rest of the page is white
- [x] FAQ Question text is 36px, bold, and #009145 
- [x] FAQ Answer text is black and 24px.
- [x] Links in the body are bold, black, and underlined.
### Copy changes:
- [x] Change heading text to match the mock-up. 1st sentence of each blurb is Regular, not Bold.
### Nice to have:
- [x] Footer with #CBCBCB background, where we credit ourselves + Citiparks + I&P for making this site.
- [x] In the mockup, I put in a blurb for sending questions to Louann, who's the official contact person. I think it's too early to stick it into our current site, but good to have once the RFP goes live.

**Comment by hamhands** [comment]
Addressed in #16
