### ISSUE TITLE
Design Mockups for Site

### ISSUE THREAD

**Issue by bsmithgall** [codeforamerica/cleaning-pgh#2]

**Comment by hamhands** [comment]
![marketing-01](https://cloud.githubusercontent.com/assets/3640800/6677732/17d6559c-cbf0-11e4-82bf-88071d8bc384.png)
![marketing-02](https://cloud.githubusercontent.com/assets/3640800/6677733/19cbed76-cbf0-11e4-9592-99a45aa67c55.png)

**Comment by hamhands** [comment]
@bsmithgall @shellicious ready for review!

**Comment by bsmithgall** [comment]
This looks pretty similar to a purecss template if you are interested in jacking that to get started: http://purecss.io/layouts/marketing/
