### ISSUE TITLE
Inline comments don't work on all lines

### ISSUE THREAD

**Issue by bsmithgall** [codeforamerica/cleaning-pgh#26]
You have to wrap everything in `<p>` tags to get this to work. There's also some weird formatting around the line item lists.

**Comment by hamhands** [comment]
How did you handle this in #14? Did you add  `<p>` tags to markdown somehow and I'm not seeing it?

**Comment by bsmithgall** [comment]
You have to do double spacing to get the paragraphs.

**Comment by hamhands** [comment]
Ah ok. Thx.

**Comment by hamhands** [comment]
Ok I added the p tags, but there are still voodoo problems with the disqus plugin. 

### Screencap

![new](https://cloud.githubusercontent.com/assets/3640800/7097920/5e4dc73c-df8f-11e4-917d-e083c38f099d.gif)
